FROM python:3
# RUN pip install pickle
WORKDIR /code
RUN apt-get update
RUN python3 -m pip install --upgrade pip setuptools wheel 
COPY ./requirement.txt ./
RUN python3 -m pip install -r requirement.txt  
# RUN pip install numpy