services:
  mysql:
    container_name: db
    image: mysql:latest
    volumes:
      - "./database/data/:/var/lib/mysql"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 256M
  composer:
    container_name: composer
    image: composer
    volumes:
      - "./web/:/code/"
    working_dir: /code/
    command: composer install
    deploy:
      resources:
        limits:
          memory: 32M    
  apache:
    container_name: web_server
    build: 
      context: ./dockerfiles/php/
    volumes:
      - "./web/:/var/www/html/"
      - ".env/:/var/www/html/.env"
    ports:
      - 80:80
    working_dir: /var/www/html/
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on:
      - python
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    deploy:
      resources:
        limits:
          memory: 64M
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
  python:
    container_name: model
    build: 
      context: ./dockerfiles/python/
    volumes:
      - "./model:/code"
    working_dir: /code/
    # environment:
    #   FLASK_DEBUG: 1
    #   FLASK_ENV: development
    #   FLASK_APP: ./server.py
    # command: flask run
    command: python3 server.py
    deploy:
      resources:
        limits:
          memory: 256M    
    depends_on:
      - mysql