services:
  mysql:
    container_name: db
    image: mysql:latest
    volumes:
      - "./database/data/:/var/lib/mysql"
    env_file:
      - .env
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          memory: 256M
  apache:
    container_name: web_server
    build: 
      context: ./dockerfiles/php/
    volumes:
      - "./web/:/var/www/html/"
      - ".env/:/var/www/html/.env"
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    deploy:
      resources:
        limits:
          memory: 75M
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
  python:
    container_name: model
    image: smizy/scikit-learn
    volumes:
      - "./model:/code"
    deploy:
      resources:
        limits:
          memory: 256M    
