services:
  mysql:
    container_name: db
    image: mysql:latest
    volumes:
      - "./database/data/:/var/lib/mysql"
    env_file:
      - .env
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          memory: 256M
  apache:
    container_name: web_server
    image: php:8.0-apache
    volumes:
      - "./web/:/var/www/html/"
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      - mysql
  python:
    container_name: model
    image: smizy/scikit-learn
    volumes:
      - "./model:/code"
    deploy:
      resources:
        limits:
          memory: 256M    
